# Use root/example as user/password credentials
version: '3.1'

services:
  web:
    build: .
    command: npm run start2
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: something
      DATABASE_HOST: db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
